### ISSUE TITLE
Methods taking coords as a `str`

### ISSUE THREAD

**Issue by majkelx** [araucaria-project/pyaraucaria#12]
in `coordinates.py` methods:

* `ra_dec_2_az_alt`
* `ra_dec_epoch`

should take `float` coordinates rather than strings in order to minimize number of `str`/`float` conversions.

Also, because this actual file is compatible with python2.7, type hinting should have form of comments.

I.e. instead of:
```python
def ra_dec_epoch(ra: str, dec: str, longitude: str, latitude: str, elevation: str, epoch:str):
    """
    Func calculates coordinates (ra, dec) for site longitude latitude elevation and epoch=now
    Parameters
    ----------
    longitude - site longitude
    latitude - site latitude
    elevation - site elevation
    ra - ra for given epoch
    dec - dec for given epoch
    epoch - epoch of (ra, dec), example: '2000/01/01', '2000'

    Returns
    -------
    (ra, dec) for epoch=now and given site
    """
```

should be sth like:  ([See PEP484](https://peps.python.org/pep-0484/#suggested-syntax-for-python-2-7-and-straddling-code))

```python
def ra_dec_epoch(ra, dec, longitude, latitude, elevation, epoch):
    # type: (float, float, float, float, float, int|Time) -> (float, float)
    """
    Calculates coordinates (ra, dec) for site longitude latitude elevation and epoch=now

    Parameters
    ----------
    longitude - site longitude (deg)
    latitude - site latitude (deg)
    elevation - site elevation (m)
    ra - right angle for given epoch (deg)
    dec - declination for given epoch (deg)
    epoch - epoch of (ra, dec), example: 2000

    Returns
    -------
    (ra, dec) for epoch=now and given site
    """
```

This is a bit urgent, because @ernestworkspace is going to use it as well.

**Comment by majkelx** [comment]
BTW, we are going to get rid of ephem.

astopy is OK, sth like:
```
coord_epoch2000 = coord.SkyCoord(ra=ra, dec=dec, unit="deg", frame="icrs", equinox="J2000")

current_time = Time.now()

coord_now = coord_epoch2000.transform_to(coord.GCRS(obstime=current_time))

ra_now = coord_now.ra.deg
dec_now = coord_now.dec.deg
```

**Comment by MMiirrkk** [comment]
Just to be clear, You want me to:
1. Change for python 2.7 type annotations.
2. All coordinates ra, dec, alt, az, lognitude, latitude, elevation -> change for floats.
3. Change below methods for astropy:
ra_dec_epoch
ra_dec_2_az_alt
site_sidereal_time
az_alt_2_ra_dec
@majkelx ?

**Comment by majkelx** [comment]
But point 2 is most important it's breakinf change.

**Comment by MMiirrkk** [comment]
> Just to be clear, You want me to:
> 
>     1. Change for python 2.7 type annotations.
> 
>     2. All coordinates ra, dec, alt, az, lognitude, latitude, elevation -> change for floats.
> 
>     3. Change below methods for astropy:
>        ra_dec_epoch
>        ra_dec_2_az_alt
>        site_sidereal_time
>        az_alt_2_ra_dec
> 
>     4. What do You mean "and ra_to_decimal removal.." from [alt az to ra dec #11 (comment)](https://github.com/araucaria-project/pyaraucaria/pull/11#issuecomment-1566118611)
>        @majkelx ?

ad. 1 Done
ad. 2 Done
Ad. 3 One method created (az_alt_2_ra_dec_astropy) but it is taking 0,5s to calculate. Ephem methods taking much less, like 0,0005s -> subject to discuss. 
Ad. 4 ?

**Comment by majkelx** [comment]
3. If for sure be optimized, but do not expect speed of ephem. 
- we can have single transformation instead of two maybe
- we may create sime transformation objects for specific EarthLocation and epoch in separate function which `@functools.lru_cache` if python3. 
- also this may be helpful: https://docs.astropy.org/en/stable/coordinates/inplace.html#astropy-coordinates-fast-in-place
- Also we can check if there are simpler and more complicated frames I.e confiding discard taking into account some atmospheric effects if we have a choice. 

4. Ra_to_decimal duplicates functionality of the existing methods

**Comment by MMiirrkk** [comment]
ra_do_decimal? Could You show me exact location of this? This in coordinates oryginally was there before me.

**Comment by majkelx** [comment]
w zasadzie, zostało w przyszłości wyelemienować `ephem` i ten temat przenoszę do #34
