### ISSUE TITLE
deg_str_to_deg is a repetition

### ISSUE THREAD

**Issue by majkelx** [araucaria-project/pyaraucaria#13]
The method  `deg_str_to_deg` duplicates functionality of the existing method `deg_to_decimal_deg` from the same file.

I would suggest removing the new one.

**Comment by MMiirrkk** [comment]
Oh sorry, i didn't noticed. Will do with next occasion.

**Comment by MMiirrkk** [comment]
@majkelx now I do remember why I created mine. Method have some error, because it can't calculate value in 'XXX:XX:XX' format:
```

w = deg_to_decimal_deg('304:18:05')
Traceback (most recent call last):
  File "/home/mirk/aprograms/pyaraucaria/pyaraucaria/coordinates.py", line 65, in deg_to_decimal_deg
    val = float(dms)
ValueError: could not convert string to float: '304:18:05'
```

**Comment by majkelx** [comment]
@MMiirrkk reopen to remove duplicated method.

**Comment by MMiirrkk** [comment]
In ocabox is removed. After check in -cli will be removed.

**Comment by MMiirrkk** [comment]
deg_str_to_deg is removed. Issue done.
