### ISSUE TITLE
Night plan parser

### ISSUE THREAD

**Issue by ernestworkspace** [araucaria-project/pyaraucaria#5]
1. metody w obs_plan_parser.py jeśli niema żadnych przeciwskazań powinny być statyczne
2. dlaczego parser polecenie sekwencji zwraca jako `{'begin_sequence': 'begin', 'all_commands': []}` nie mogło by być naprzykład jak w pozostałych `{'command_name': 'SEQUENCE', ...`

**Comment by MMiirrkk** [comment]
Odp. 2 Przyznam się, że pracowałem na rozwiązaniach które już były i nie zastanawiałem się nad tym. Przyjrzę się bo już nie pamiętam i odpowiem.

**Comment by MMiirrkk** [comment]
Po dyskusji z @ernestworkspace :
1. Głowna sewkencja nie będzie listą, tylko będzie wrzucona w SEQUENCE.
2. Zmiana i ujednolicenie nazw w dict:
było:
{'begin_sequence': 'begin', 'all_commands': [
                {'command_name': 'WAIT', 'kwargs': {'ut': '16:00'}}
ma być:
{'**command_name**': '**SEQUENCE**', '**subcommands**: [
                {'command_name': 'WAIT', 'kwargs': {'ut': '16:00'}}

**Comment by MMiirrkk** [comment]
Powyższe punkty 1 i 2 wprowadzone w wersji 
name='pyaraucaria',
version='2.7.9',
Dla przykładów -> patrz test_obs_plan_parser.py
UWAGA! Braking change - szczególnie Marek
@majkelx @astromg @ernestworkspace

**Comment by ernestworkspace** [comment]
Dobrze by było żeby klasa `ObsPlanParser` była tylko opakowaniem i do jej używania nie było konieczne powoływanie instancji tej klasy.

**Comment by MMiirrkk** [comment]
Klasa ObsPlanParser jest opakowaniem - version='2.7.10',
