### ISSUE TITLE
Fits Header dev

### ISSUE THREAD

**Issue by MMiirrkk** [araucaria-project/pyaraucaria#9]
Poniżej wstawiam ostatnie ustalenia na temat fits header z maila 23.04.2023, 1:14 od Pauliny Kaczmarek:

- Rozpoczęcie ekspozycji sczytywane jest z kamery jako otwarcie migawki i zapisywane w czasie UT w headerze w keywordzie DATE-OBS w formacie 'YYYY-MM-DDThh:mm:ss.sss'
- Na chwilę obecną data zakończenia obserwacji ani zapisu pliku nie jest zaimplementowana.
- W pole OBSERVER wpisywać będą się obserwatorzy obecnie przebywający na "szychcie". Pole to będzie dostępne do edycji w programie zarządzającym obserwacjami i może się świecić na czerwono jeśli jest niewypełnione.

- Pole OBS-PROG będzie przeznaczone do wpisania projektu naukowego, w ramach którego dane dane są zbierane, np. 'T2Cep'. Nazwy projektów będą ustandaryzowane i w przyszłości, na przykład, dostępne z listy.
- Mieliśmy dłuższą dyskusję przy keywordzie OBSTYPE oraz jego wartości opisującej ekspozycję typu bias. Nie uzgodniliśmy finalnie czy przyjąć wartość 'bias' czy 'zero'; na decyzję może wpłynąć to, jak IRAF rozpoznaje ekspozycje bias. Wg tej strony internetowej  (http://www.physics.hmc.edu/Astronomy/Ireduce.html) IRAF wyszukuje ekspozycje bias po keywordzie IMAGETYP i wartości 'zero'. Proponuję więc zmienić aktualny keyword OBSTYPE na IMAGETYP i przypisać mu jedną z następujących wartości rozpoznawanych przez IRAFa: zero, flat, dark, lub wartości, które dla nas będą miały znaczenie: object, focus.
- W polu CCD_NAME będzie wpisana pełna nazwa kamery, tj. 'Andor iKon-L DW936_BV'
- Keyword GAIN został zastąpiony keywordem GAIN_MOD, a jego wartość jak poprzednio jest sczytywana z kamery i wynosi '4x', '2x' albo '1x'.
- Keyword GAIN będzie mieć wartość wyrażoną w [e-/ADU], która została wyznaczona przez Stefana Kimeswengera, ta wartość jest różna dla różnych GAIN_MOD i wynosi:
    *   GAIN=3.93e-/ADU dla GAIN_MOD='x1'
    *   GAIN=1.93e-/ADU dla GAIN_MOD='x2'
    *   GAIN=0.97e-/ADU dla GAIN_MOD='x4'
- Keyword RNOISE będzie zastąpiony przez RON i wyrażony w [e-/read]. RON zależy od GAIN_MOD (3 możliwości) oraz READ_MOD (4 możliwości), co daje łącznie 12 kombinacji. Na razie poznaliśmy wartości RON dla 4 kombinacji (dzięki raportowi Stefana Kimeswengera).
- Informacja o binowaniu kamery znajduje się w dwóch osobnych keywordach: CCDBINX oraz CCDBINX
- Informacja o liczbie ekspozycji w jednej serii oraz numerze ekspozycji w danej serii zawarta jest w keywordach NLOOPS oraz LOOP. Te pola przydadzą się przy flatach, darkach i biasach oraz niektórych ekspozycjach naukowych, gdzie będziemy potrzebować więcej ekspozycji do uśrednienia.
- Pole COMMENT najczęściej pozostanie puste, ale będzie wypełniane automatycznie w przypadku problemów z obserwacją (przerwana obserwacja, wyłączony tracking i inne problemy "automatyczne").
- Może OBSTYP dać tylko wartości science, test, calib (oraz "art" dla Mirka, może tez być "training" etc), a IMGTYPE tak jak Paulina napisała? Przyda się do zgrubnego sortowania. 

Na koniec chciałabym zawrzeć jeszcze propozycje keywordów, których co prawda nie omawialiśmy, ale które mogą być przydatne:

SCALE   =              0.5 / [arcsec/pixel]
SATURATE=            65535 / Data value at which saturation occurs
RADECSYS=            'FK5' / Coordinate reference frame # (typically 'FK5' or the  preferred 'ICRS')

Dajcie znać co myślicie o zamianie keywordu OBSTYPE na IMAGETYP, o dorobieniu wartości RON dla wszystkich kombinacji oraz o dodatkowych propozycjach keywordów powyżej.

@majkelx @astromg @ernestworkspace @pkarczmarek

**Comment by MMiirrkk** [comment]
I jeszcze przykład od Pauliny:

SIMPLE  =                T / Fits format                                    
BITPIX  =               16 / bits per pixel                                 
NAXIS   =                2 / number of axes                                 
NAXIS1  =             2048 / image width                                    
NAXIS2  =             2048 / image height                                   
BSCALE  =            1.000 / physical = BZERO + BSCALE*array_value
BZERO   =            32768 / physical = BZERO + BSCALE*array_value
OCASTD  =          'BETA2' / OCA FITS HDU standard version
ORIGIN  =       'CAMK PAN' / Institution responsible for the data
OBSERVAT=            'OCA' / Cerro Armazones Observatory
OBS-LAT =       -24.598056 / [deg] Observatory longitude -24:35:53
OBS-LONG=       -70.196389 / [deg] Observatory latitude -70:11:47
OBS-ELEV=           2817.0 / [m] Observatory elevation
TELESCOP=           'zb08' / Name of telescope
OBSERVER= 'LastName1, LastName2' / Observers who acquired the data
DATE-OBS= 'YYYY-MM-DDThh:mm:ss.sss' / Observation start UT
JD      = fffffff.ffffffff / Observation start Julian Date
RA      =        ff.ffffff / [deg] R.A. of the telescope pointing
DEC     =        ff.ffffff / [deg] Declination of the telescope pointing
ALT     =        ff.ffffff / [deg] Altitude of the observation
AZ      =        ff.ffffff / [deg] Azimuth of the observation
AIRMASS =            f.fff / Airmass
OBJ_RA  =        ff.ffffff / [deg] R.A. of the observed object
OBJ_DEC =        ff.ffffff / [deg] Declination of the observation 
EQUINOX =           2000.0 / Epoch of RA_OBJ DEC_OBJ
OBJ_ALT =        ff.ffffff / [deg] Altitude of the observed object
OBJ_AZ  =        ff.ffffff / [deg] Azimuth of the observed object
IMAGETYP=       'ssssssss' / Image type: zero, flat, dark, object, focus
OBSMODE =       'ssssssss' / Observ. mode: TRACKING, GUIDING, JITTER, ELSE
OBJECT  =         'ssssss' / Name of observed object
EXPREQ  =           ffff.f / [s] Requested exposure time
EXPTIME =           ffff.f / [s] Executed exposure time
OBS-PROG=         'ssssss' / Name of the science project
NLOOPS  =                5 / Number of all exposures in this sequence
LOOP    =                3 / Number of exposure within this sequence
FILTER  =         'ssssss' / Filter
FOCUS   =            ddddd / [mm] Focus position
ROTATOR =      ss.ssssssss / [deg] Rotator position
CCD_TEMP=       fff.ffffff / [degC] Camera temperature							# our chosen operational temp. -65 degC
GAIN    =             f.ff / [electrons/ADU]
RON     =            ff.ff / [electrons/read] Read out noise 
READ_MOD= '1MHz High Sensitivity 16-bit' / Mode of read out speed from camera
GAIN_MOD=                 '4x' / Mode of Gain read from camera  
CCD_NAME= 'Andor iKon-L DW936_BV' / Name of camera
SUBRASTR=      '1:2048,1:2048' / subraster x1:x2,y1:y2
CCD_BINX=                    1 / Camera binning in x-axis                                                 
CCD_BINY=                    1 / Camera binning in y-axis                                                
COMMENT = '                  ' / Inf. about perform. of telescope
END                                                                             

optional or for the future:
DATE    = 'YYYY-MM-DDThh:mm:ss.sss' / Date this file was created UT
DATE-END= 'YYYY-MM-DDThh:mm:ss.sss' / Date of the end of observation UT
SCALE   =              0.5 / [arcsec/pixel]
SATURATE=            ddddd / Data value at which saturation occurs				# depends on GAIN_MOD (as calculated by Stefan)
RADECSYS=           'ssss' / Coordinate reference frame							# (typically 'FK5' or the  preferred 'ICRS')

**Comment by WojtekPych** [comment]
FITS headers from gui-text and TOI have different information about the GAIN setting. For instance gui-text writes '2x' and TOI writes '1' for the same setting.

**Comment by WojtekPych** [comment]
Why are there trailing spaces between apostrophes?

**Comment by WojtekPych** [comment]
The information about the position of the dome is missing in the headers.

**Comment by WojtekPych** [comment]
There should be full information in the headers for calibration frames. For instance filter name is missing in zero and dark frames.

**Comment by WojtekPych** [comment]
There is a bug in the DATE-OBS - there should be 'T' not space between the day and the hour.

**Comment by MMiirrkk** [comment]
> There is a bug in the DATE-OBS - there should be 'T' not space between the day and the hour.

Done

**Comment by MMiirrkk** [comment]
FIts header dev is still in progress.

**Comment by majkelx** [comment]
Może #28 wystarczy?
